# ===========================================
# Site Settings 网站相关设置
# ===========================================

# 网站基础设置
# 图片需要放置在 themes/pinghsu/source/imagse 下
headerLogoUrl: # 头部左上角logo图片地址，留空则取网站标题 
footerLogoUrl: 
lowerleftLogo: /images/lowerleft_1.png # /images/lowerleft_2.png # 左下角图片，留空则不设 lowerleftLogo
favicon: /images/favicon.png # favicon(即chrome标签页图标)，留空则不设favicon
iosicon: /images/apple-touch-icon.png # apple touch icon 地址，留空则不设 apple touch icon
since: 2017 # 站点起始时间

# Menu Setting 菜单设置。由于标签和分类重复，所以默认关闭标签页。
menu:
  home: /
#  categories: /categories
  tags: /tags
  archives: /archives
  links: /links
  about: /about
  gallery: /gallery
  # resume: /resume

# Social Setting 社交设置
social:
  Github: https://github.com/huangyebiaoke
  QQ: https://wpa.qq.com/msgrd?v=3&uin=1536711290&site=qq&menu=yes
  Email: mailto:huangyebiaoke@outlook.com
  Weibo: https://weibo.com/5910563005/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1
  Zhihu: https://www.zhihu.com/people/hu-zhong-xin-14
  Bilibili: https://space.bilibili.com/56733506/#/
  Douban: https://www.douban.com/people/176806943/
  Twitter: https://twitter.com/1536711290M?s=09
  Linkedin: https://www.linkedin.com/in/%E5%AE%9A%E6%98%8E-%E6%9D%A8-47a876155/
  Tumblr: https://www.tumblr.com/blog/minghere
  RSS: /atom.xml

# ===========================================
# Function Setting 功能设置
# ===========================================

# 是否启用DNS预解析加速
# 启用则会对CDN资源和Gravatar进行加速
dnsPrefetch: true

# 自定义CDN加速地址
# 若设置，且启用DNS预解析，则会被加速，可以填写图床地址进行图片加载加速，或者加速其他cdn
cdnAdd: ws1.sinaimg.cn

# 是否启用移动端点击延迟消除设置
enableFastClick: true

# 是否启用文章Mathjax设置
# 启用则会对内容页进行数学公式渲染，仅支持 $公式$ 和 $$公式$$
enableMathjax: true

# 文章页底部相关文章设置
# 仅在文章页中生效，文章是根据标签进行相关的
# enable：是否启用
# limit：显示文章数量，建议设置不超过6条
relatedPosts: 
  enable: true
  limit: 3

# 底部最近文章设置
# enable：是否启用
# limit：显示数量，建议设置不超过8条
recentlyPosts:
  enable: true
  limit: 5

# 底部最近评论设置
# 只有开启了valine评论系统才能生效
# enable：是否启用
# limit：显示数量，建议设置不超过8条
recentlyComments:
  enable: false
  limit: 5

# ===========================================
# Appearance Setting 外观设置
# ===========================================

# 首页文章列表设置
# 默认三列
# three: 三列，one：一列
postListSwitch: three

# 文章色块设置
# 启用则可以通过文章字段color控制色块颜色，仅支持blue、purple、green、yellow、red
colorBgPosts: true

# 文章题图设置
# 启用则在文章页顶部显示缩略图
showPostThumb: true

# 默认缩略图
defaultThumb: 

# 随机缩略图设置
# 设为 0 则不使用主题自带的缩略图，转而使用个性化色块
# 不为 0 时表示默认随机缩略图的数量
randomThumb: 18

# 文章目录设置
# 文章页右边目录生成，仅在网页宽度大于1000px时显示
enableDirectory: true

# 代码高亮设置
# enable：是否启用
# theme：主题样式css名称，默认使用atom-one-dark主题。在https://highlightjs.org/static/demo/上可以修改
highlight:
  enable: true
  theme: atom-one-light

# 底部彩色动态词语配置
# 一个词语一行
animateWords:
  - Java
  - Android
  - SpringBoot

# 不蒜子网站统计
busuanzi: true

# 百度统计id，填写复 hm.js? 后面那串统计脚本 id
baiduAnalytics: fda70a9fbd113c8f1905fe991a5d593a

# 网站备案信息
beian: 赣ICP备17011914号

# valine评论系统
# 配置详情参考：https://valine.js.org/configuration.html
valine:
  enable: false # 是否启用
  appId: 
  appKey: 
  placeholder: 说点什么吧~ # 输入框默认显示文本
  pageSize: 10 # 每页评论数量
  avatar: mp # 头像类型
  visitor: true # 文章阅读量统计
# gitalk
gitalk:
  enable: true
  owner: huangyebiaoke
  repo: huangyebiaoke.github.io
  client_id: 23abedc384baaed0f181
  client_secret: a0b5098dcff025e49c424ba1cbe5cd3684b6822f
  admin: huangyebiaoke

# 打赏配置
# 二维码图片放置在主题目录下的/source/imagse/
# example：/images/wechat.jpg
reward:
  enable: true # 是否启用
  text: 看了这么久,不请我喝杯茶吗? # 打赏文案
  wechat: /assets/img/weixin.png # 微信支付二维码地址
  alipay: /assets/img/alipay.jpg # 支付宝二维码地址

# 文章页音乐播放器设置
# 配置详情参考：https://github.com/metowolf/MetingJS
music:
  enable: true # 是否启用
  id: 573623248 # song id / playlist id / album id / search keyword
  server: netease # music platform: netease, tencent, kugou, xiami, baidu
  type: playlist # song, playlist, album, search, artist
  autoplay: false # 是否使用自动播放
  fixed: false  # 是否使用固定模式
  mini: false # 是否使用迷你模式
  order: random # list: 顺序播放 random: 随机播放

# Main page 
index_generator:
  path: ''
  per_page: 12
  order_by: -date

# Archive Setting 归档页设置
# month: 按月份归档，year: 按年份归档，默认按月份归档
archive: year
# Archive page
archive_generator:
  enabled: true
  per_page: 12
  yearly: true
  monthly: false
  daily: false
  order_by: -date

# Categories and detail
category_generator:
  per_page: 12

tag_generator:
  per_page: 12

# 插件及特效设置
# 显示看板娘
live2d:
  enable: false

# 本地搜索
local_search:
  address: /search

# 点击烟花爆炸效果
click_fireworks:
  enable: false

# 网站点击红心效果
click_love: 
  enable: false

# 超链接平滑移动
smooth_scroll:
  enable: true